name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Manual Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      # Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - name: Storybook to Github Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: pnpm install
          build_command: pnpm run storybook:build
          path: storybook-static
          checkout: false
